version: '3'
services:
  zookeeper:
    image: "bitnami/zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "22181:2181"

  kafka:
    image: "bitnami/kafka"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  spark:
    image: bitnami/spark:latest
    ports:
      - "28080:8080"
    depends_on:
      - kafka
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_OPTS="-Dspark.driver.memory=2g -Dspark.executor.memory=2g"
    volumes:
      - /Users/i070883/Documents/LBNApp/datatransform/target/dataprocess-0.0.1-SNAPSHOT-jar-with-dependencies.jar:/usr/apps/dataprocess.jar
  spark-worker:
    image: "bitnami/spark:latest"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark
      - cassandra

  cassandra:
    image: cassandra:latest
    ports:
      - '9042:9042' # native protocol clients