version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  spark:
    image: bitnami/spark:3.1.2
    ports:
      - "4040:4040"
    depends_on:
      - kafka
    environment:
      SPARK_MASTER_URL: spark://spark:7077
      SPARK_APPLICATION_ARGS: "kafka:9092"

  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"

  java_app:
    build:
      context: ./dataprocess/target/
    depends_on:
      - kafka
    command: ["java", "-jar", "dataprocess-0.0.1-SNAPSHOT.jar", "<your_app_arguments>"]

networks:
  default:
    external:
      name: bridge
